### ISSUE TITLE
Add missing post information when retrieve all posts

### ISSUE THREAD

**Issue by YuryDG** [lealceldeiro/org.wcdevs.blog.core#62]
### What new feature you'd like to see provided by API?

Retrieve post information when calling endpoint GET /post

Add this information to the response for **each post**
- body
- publishedOn
- updatedOn
- publishedBy
- updatedBy

API documentation [here](https://api.wcdevs.org/docs/index.html#resource-post-list)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lealceldeiro** [comment]
For now `body` won't be returned in this endpoints, since it can contain a very large amount of data without the users actually entering the post to ready it. For the rest of the fields it'll be implemented.
